name: ifruit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  flutter_soloud: ^4.1.3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  fluttertoast: ^10.0.0
  sqflite: ^2.4.3
  path_provider: ^2.1.6
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/audios/
    - assets/data/
    - assets/icons/avatar/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app.png"
